# -*- coding: utf-8 -*-
"""heart.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18o0RQnCg16n0qHFbb1_eOM6mDC7NI8ib

# Magdy Mohamed

# Data Description :

# Attribute Information
1-Age: age of the patient [years]

2-Sex: sex of the patient [M: Male, F: Female]

3-ChestPainType: chest pain type [TA: Typical Angina, ATA: Atypical Angina, NAP: Non-Anginal Pain, ASY: Asymptomatic]

4-RestingBP: resting blood pressure [mm Hg]

5-Cholesterol: serum cholesterol [mm/dl]

6-FastingBS: fasting blood sugar [1: if FastingBS > 120 mg/dl, 0: otherwise]

7-RestingECG: resting electrocardiogram results [Normal: Normal, ST: having ST-T wave abnormality (T wave inversions and/or ST elevation or depression of > 0.05 mV), LVH: showing probable or definite left ventricular hypertrophy by Estes' criteria]

8-MaxHR: maximum heart rate achieved [Numeric value between 60 and 202]

9-ExerciseAngina: exercise-induced angina [Y: Yes, N: No]

10-Oldpeak: oldpeak = ST [Numeric value measured in depression]

11-ST_Slope: the slope of the peak exercise ST segment [Up: upsloping, Flat: flat, Down: downsloping]

12-HeartDisease: output class [1: heart disease, 0: Normal]

# Context
Cardiovascular diseases (CVDs) are the number 1 cause of death globally, taking an estimated 17.9 million lives each year, which accounts for 31% of all deaths worldwide. Four out of 5CVD deaths are due to heart attacks and strokes, and one-third of these deaths occur prematurely in people under 70 years of age. Heart failure is a common event caused by CVDs and this dataset contains 11 features that can be used to predict a possible heart disease.

People with cardiovascular disease or who are at high cardiovascular risk (due to the presence of one or more risk factors such as hypertension, diabetes, hyperlipidaemia or already established disease) need early detection and management wherein a machine learning model can be of great help.

# Importing libraries :
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""## Import the dataset"""

df=pd.read_csv('/content/heart.csv')
df.head()

"""EDA"""

df.info()

df.describe()

df.isnull().sum()

df.duplicated().sum()

plt.figure(figsize=(12, 7))
heartDisease_countplot = sns.countplot(x=df.HeartDisease,palette=["#CD5C5C","#BDB76B"])
heartDisease_countplot.set_title("Distribution of Target 'Heart Disease'")
heartDisease_countplot.set_xticklabels(['No', 'Yes'], fontsize=20)

sns.countplot(data=df,x='Sex' , palette=['pink','brown']);
plt.title('Sex Distribution')
plt.xlabel('Sex')
plt.ylabel('Count')

Categorical = df.select_dtypes(include=['object'])
Numerical = df.select_dtypes(include=['int64', 'float64'])

# ploting numerical features with target
#here we compare betwwen our target and our numerical features
for i in Numerical:
    plt.figure(figsize=(10,5))
    sns.countplot(x=i, data=df, hue='HeartDisease')
    plt.legend(['Normal', 'Heart Disease'])
    plt.title(i)
    plt.show()

#here we compare betwwen our target and our Categorical features
for i in Categorical:
    plt.figure(figsize=(10,10))
    sns.countplot(x=i, data=df, hue='HeartDisease', edgecolor='black')
    plt.legend(['Normal', 'Heart Disease'])
    plt.title(i)
    plt.show()

"""# Handeling with outliers :"""

df.plot(kind='box',figsize=(15,10),subplots=True,layout=(3,3))
plt.show()

"""after the boxplot we find that the outliers here in (age - restingBP-cholesterol-MaxHR-oldpeak)"""

df_out = ['Age', 'RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']

#here we are detecting outliers :

def find_outliers_IQR(df):

   q1=df.quantile(0.25)

   q3=df.quantile(0.75)

   IQR=q3-q1

   outliers = df[((df<(q1-1.5*IQR)) | (df>(q3+1.5*IQR)))]

   return outliers

#here we are trying to find the numbers of outliers and max and min of them to can detect them clearly:
outliers = find_outliers_IQR(df['RestingBP'])
print('number of outliers: '+ str(len(outliers)))

print('max outlier value: '+ str(outliers.max()))

print('min outlier value: '+ str(outliers.min()))

for char in df_out :
    outliers = find_outliers_IQR(df[str(char)])

    print(f"-Check {char} outliers ")

    print('number of outliers: '+ str(len(outliers)))

    print('max outlier value: '+ str(outliers.max()))

    print('min outlier value: '+ str(outliers.min())+ '\n')

# remove outliers
def remove_outliers_IQR(df, columns):
    df_cleaned = df.copy()
    for col in columns:
        Q1 = df_cleaned[col].quantile(0.25)
        Q3 = df_cleaned[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_cleaned = df_cleaned[~((df_cleaned[col] < lower_bound) | (df_cleaned[col] > upper_bound))]
    return df_cleaned

df_out = ['RestingBP', 'Cholesterol', 'MaxHR', 'Oldpeak']
df = remove_outliers_IQR(df, df_out)
print("Original shape:", df.shape)
print("Shape after outlier removal:", df.shape)

"""# Encoding categorical features:"""

from sklearn.preprocessing import LabelEncoder
ChestPainType_le = LabelEncoder()
RestingECG_le = LabelEncoder()
ExerciseAngina_le = LabelEncoder()
ST_Slope_le = LabelEncoder()
Sex_le = LabelEncoder()

df['ChestPainType'] = ChestPainType_le.fit_transform(df['ChestPainType'])

ChestPainType_le.classes_

df['RestingECG'] = RestingECG_le.fit_transform(df['RestingECG'])

RestingECG_le.classes_

df['ST_Slope'] = ST_Slope_le.fit_transform(df['ST_Slope'])

ST_Slope_le.classes_

df['ExerciseAngina'] = ExerciseAngina_le.fit_transform(df['ExerciseAngina'])

ExerciseAngina_le.classes_

df['Sex'] = Sex_le.fit_transform(df['Sex'])

Sex_le.classes_

df.info()

"""## Spliting data:"""

X = df.drop(columns=['HeartDisease'])
y = df['HeartDisease']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
std_scaler.fit(X)
X_train_std=std_scaler.transform(X_train)
X_test_std=std_scaler.transform(X_test)

X_train = pd.DataFrame(X_train_std, columns=X.columns)
X_test = pd.DataFrame(X_test_std, columns=X.columns)

display(X_train.head())
display(X_test.head())

"""# Modeling by different methods  :

## Training the Logistic Regression model on the Training set
"""

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 44)
lr.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = lr.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""## Confusion Matrix and Evaluation

"""

from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
cm1 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm1, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""## Training the K-NN model on the Training set"""

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = knn.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""# Confusion Matrix and Evaluation

"""

cm2 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm2, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""## Training the SVM model on the Training set"""

from sklearn.svm import SVC
svm = SVC(kernel = 'linear', random_state = 44)
svm.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = svm.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""## Confusion Matrix and Evaluation

"""

cm3 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm3, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""## Training the Kernel SVM model on the Training set"""

from sklearn.svm import SVC
k_svm = SVC(kernel = 'rbf', random_state = 44)
k_svm.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = k_svm.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""## Confusion Matrix and Evaluation

"""

cm4 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm4, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""## Training the Naive Bayes model on the Training set"""

from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = nb.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""## Confusion Matrix and Evaluation

"""

cm5 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm5, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""## Training the Decision Tree Classification model on the Training set"""

from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 44)
dt.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = dt.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""## Confusion Matrix and Evaluation

"""

cm6 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm6, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""## Training the Random Forest Classification model on the Training set"""

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 44)
rf.fit(X_train, y_train)

"""## Predicting the Test set results"""

y_pred = rf.predict(X_test)
data = pd.DataFrame({"y_test" : y_test , "y_pred": y_pred})
data.head(10)

"""## Confusion Matrix and Evaluation

"""

cm7 = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(6,6))
sns.heatmap(cm7, annot=True, fmt='d', cmap='Blues')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))

"""# Magdy Mohamed"""